var extensions = {
	"csv": "csv",
	"tsv": "meta",
	"dsv": "meta",
	"groovy": "groovy",
	"ini": "properties",
	"properties": "properties",
	"css": "css",
	"scss": "css",
	"html": "htmlmixed",
	"htm": "htmlmixed",
	"shtm": "htmlmixed",
	"shtml": "htmlmixed",
	"xhtml": "htmlmixed",
	"cfm": "htmlmixed",
	"cfml": "htmlmixed",
	"cfc": "htmlmixed",
	"dhtml": "htmlmixed",
	"xht": "htmlmixed",
	"tpl": "htmlmixed",
	"twig": "htmlmixed",
	"hbs": "htmlmixed",
	"handlebars": "htmlmixed",
	"kit": "htmlmixed",
	"jsp": "htmlmixed",
	"aspx": "htmlmixed",
	"ascx": "htmlmixed",
	"asp": "htmlmixed",
	"master": "htmlmixed",
	"cshtml": "htmlmixed",
	"vbhtml": "htmlmixed",
	"ejs": "htmlembedded",
	"dust": "htmlembedded",
	"erb": "htmlembedded",
	"js": "javascript",
	"jsx": "javascript",
	"jsm": "javascript",
	"_js": "javascript",
	"vbs": "vbscript",
	"vb": "vb",
	"json": "javascript",
	"xml": "xml",
	"svg": "xml",
	"wxs": "xml",
	"wxl": "xml",
	"wsdl": "xml",
	"rss": "xml",
	"atom": "xml",
	"rdf": "xml",
	"xslt": "xml",
	"xsl": "xml",
	"xul": "xml",
	"xbl": "xml",
	"mathml": "xml",
	"config": "xml",
	"plist": "xml",
	"xaml": "xml",
	"php": "php",
	"php3": "php",
	"php4": "php",
	"php5": "php",
	"phtm": "php",
	"phtml": "php",
	"ctp": "php",
	"c": "clike",
	"h": "clike",
	"i": "clike",
	"cc": "clike",
	"cp": "clike",
	"cpp": "clike",
	"c++": "clike",
	"cxx": "clike",
	"hh": "clike",
	"hpp": "clike",
	"hxx": "clike",
	"h++": "clike",
	"ii": "clike",
	"ino": "clike",
	"cs": "clike",
	"asax": "clike",
	"ashx": "clike",
	"java": "clike",
	"scala": "clike",
	"sbt": "clike",
	"coffee": "coffeescript",
	"cf": "coffeescript",
	"cson": "coffeescript",
	"_coffee": "coffeescript",
	"clj": "clojure",
	"cljs": "clojure",
	"cljx": "clojure",
	"pl": "perl",
	"pm": "perl",
	"rb": "ruby",
	"ru": "ruby",
	"gemspec": "ruby",
	"rake": "ruby",
	"py": "python",
	"pyw": "python",
	"wsgi": "python",
	"sass": "sass",
	"lua": "lua",
	"sql": "sql",
	"diff": "diff",
	"patch": "diff",
	"md": "markdown",
	"markdown": "markdown",
	"mdown": "markdown",
	"mkdn": "markdown",
	"yaml": "yaml",
	"yml": "yaml",
	"hx": "haxe",
	"sh": "shell",
	"command": "shell",
	"bash": "shell"
}

var sublimeBindings = {
	"Ctrl-Space": "test",
	"Alt-F2": "selectBookmarks",
	"Alt-Left": "goSubwordLeft",
	"Alt-Q": "wrapLines",
	"Alt-Right": "goSubwordRight",
	"Alt-W": "wrapLines",
	"Backspace": "smartBackspace",
	"Ctrl-/": "toggleCommentIndented",
	"Ctrl-D": "duplicateLine",
	"Ctrl-Enter": "insertLineAfter",
	"Ctrl-Shift-Enter": "insertLineBefore",
	"Ctrl-F": "findUnder",
	"Ctrl-F2": "toggleBookmark",
	"Ctrl-F3": "findUnder",
	"Ctrl-F5": "sortLinesInsensitive",
	"Ctrl-F9": "sortLinesInsensitive",
	"Ctrl-H": "replace",
	"Ctrl-J": "joinLines",
	"Ctrl-K Ctrl-0": "unfoldAll",
	"Ctrl-K Ctrl-A": "selectToSublimeMark",
	"Ctrl-K Ctrl-Backspace": "delLineLeft",
	"Ctrl-K Ctrl-C": "showInCenter",
	"Ctrl-K Ctrl-G": "clearBookmarks",
	"Ctrl-K Ctrl-J": "unfoldAll",
	"Ctrl-K Ctrl-K": "delLineRight",
	"Ctrl-K Ctrl-L": "downcaseAtCursor",
	"Ctrl-K Ctrl-Space": "setSublimeMark",
	"Ctrl-K Ctrl-U": "upcaseAtCursor",
	"Ctrl-K Ctrl-W": "deleteToSublimeMark",
	"Ctrl-K Ctrl-X": "swapWithSublimeMark",
	"Ctrl-K Ctrl-Y": "sublimeYank",
	"Ctrl-L": "splitSelectionByLine",
	"Ctrl-M": "goToBracket",
	"Ctrl-Shift-[": "fold",
	"Ctrl-Shift-]": "unfold",
	"Ctrl-Shift-D": "selectNextOccurrence",
	"Ctrl-Shift-F2": "clearBookmarks",
	"Ctrl-Shift-F3": "findUnderPrevious",
	"Ctrl-Shift-K": "deleteLine",
	"Ctrl-Shift-L": "selectLine",
	"Ctrl-Shift-M": "selectBetweenBrackets",
	"Ctrl-Shift-Space": "selectScope",
	"Ctrl-T": "transposeChars",
	"Enter": "newlineAndIndentContinueMarkdownList",
	"Esc": "singleSelectionTop",
	"F2": "nextBookmark",
	"F5": "sortLines",
	"F9": "sortLines",
	"Shift-F2": "prevBookmark",
	"Shift-Tab": "indentLess",
	"Tab": "indentMore",
	"Ctrl-Shift-Up": "swapLineUp",
	"Ctrl-Shift-Down": "swapLineDown",
	"Ctrl-Alt-Up": "scrollLineUp",
	"Ctrl-Alt-Down": "scrollLineDown",
	"Ctrl-Up": "addCursorToPrevLine",
	"Ctrl-Down": "addCursorToNextLine",
	"Shift-Up": "selectLinesUpward",
	"Shift-Down": "selectLinesDownward",
}
function options() {
	return {
		format: {
			indent: {
				style: $('#indentStyle').val().toString(),
				base: $('#baseIndent').val().toInt(),
				adjustMultilineComment: false
			},
			newline: '\n',
			space: ' ',
			json: false,
			renumber: false,
			hexadecimal: false,
			quotes: $('#quotes').val().toString(),
			escapeless: false,
			compact: false,
			parentheses: true,
			semicolons: $('#semicolons').is(':checked'),
			bracketFormat: $('#bracketFormat').is(':checked')
		},
		parse: null
	}
}